# permissions for end users to edit quotas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: quota-operator
    app.kubernetes.io/managed-by: kustomize
  name: quota-editor-role
rules:
- apiGroups:
  - kmc.kmc.io
  resources:
  - quotas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kmc.kmc.io
  resources:
  - quotas/status
  verbs:
  - get
